// Production-ready downloads mapping – activate by renaming to downloads.ts
// and removing/renaming the old downloads.ts

import type { DownloadItem } from "@/lib/downloads"

const PREFIX = "downloads/library/prod"

const BASIC_ITEMS: DownloadItem[] = [
  { name: "forschungsdesign grundlagen", description: "Download: forschungsdesign grundlagen", fileUrl: `${PREFIX}/basic_01_de_forschungsdesign_grundlagen.docx` },
  { name: "pruefung forschungsdesign grundlagen", description: "Download: pruefung forschungsdesign grundlagen", fileUrl: `${PREFIX}/basic_01_de_pruefung_forschungsdesign_grundlagen.docx` },
  { name: "spickzettel", description: "Download: spickzettel", fileUrl: `${PREFIX}/basic_01_de_spickzettel.docx` },
  { name: "wörterbuch", description: "Download: wörterbuch", fileUrl: `${PREFIX}/basic_01_de_wörterbuch.docx` },
  { name: "cheatsheet", description: "Download: cheatsheet", fileUrl: `${PREFIX}/basic_01_en_cheatsheet.docx` },
  { name: "dictionary", description: "Download: dictionary", fileUrl: `${PREFIX}/basic_01_en_dictionary.docx` },
  { name: "exam research design basics", description: "Download: exam research design basics", fileUrl: `${PREFIX}/basic_01_en_exam_research_design_basics.docx` },
  { name: "research design basics", description: "Download: research design basics", fileUrl: `${PREFIX}/basic_01_en_research_design_basics.docx` },
  { name: "pruefung stichprobenverfahren", description: "Download: pruefung stichprobenverfahren", fileUrl: `${PREFIX}/basic_02_de_pruefung_stichprobenverfahren.docx` },
  { name: "stichprobenverfahren", description: "Download: stichprobenverfahren", fileUrl: `${PREFIX}/basic_02_de_stichprobenverfahren.docx` },
  { name: "exam sampling methods", description: "Download: exam sampling methods", fileUrl: `${PREFIX}/basic_02_en_exam_sampling_methods.docx` },
  { name: "sampling methods", description: "Download: sampling methods", fileUrl: `${PREFIX}/basic_02_en_sampling_methods.docx` },
  { name: "messtheorie operationalisierung", description: "Download: messtheorie operationalisierung", fileUrl: `${PREFIX}/basic_03_de_messtheorie_operationalisierung.docx` },
  { name: "pruefung messtheorie operationalisierung", description: "Download: pruefung messtheorie operationalisierung", fileUrl: `${PREFIX}/basic_03_de_pruefung_messtheorie_operationalisierung.docx` },
  { name: "exam measurement theory", description: "Download: exam measurement theory", fileUrl: `${PREFIX}/basic_03_en_exam_measurement_theory.docx` },
  { name: "measurement theory", description: "Download: measurement theory", fileUrl: `${PREFIX}/basic_03_en_measurement_theory.docx` },
  { name: "explorative datenanalyse", description: "Download: explorative datenanalyse", fileUrl: `${PREFIX}/basic_04_de_explorative_datenanalyse.docx` },
  { name: "pruefung explorative datenanalyse", description: "Download: pruefung explorative datenanalyse", fileUrl: `${PREFIX}/basic_04_de_pruefung_explorative_datenanalyse.docx` },
  { name: "exam exploratory data analysis", description: "Download: exam exploratory data analysis", fileUrl: `${PREFIX}/basic_04_en_exam_exploratory_data_analysis.docx` },
  { name: "exploratory data analysis", description: "Download: exploratory data analysis", fileUrl: `${PREFIX}/basic_04_en_exploratory_data_analysis.docx` },
  { name: "datenvisualisierung", description: "Download: datenvisualisierung", fileUrl: `${PREFIX}/basic_05_de_datenvisualisierung.docx` },
  { name: "pruefung datenvisualisierung", description: "Download: pruefung datenvisualisierung", fileUrl: `${PREFIX}/basic_05_de_pruefung_datenvisualisierung.docx` },
  { name: "data visualization", description: "Download: data visualization", fileUrl: `${PREFIX}/basic_05_en_data_visualization.docx` },
  { name: "diskrete verteilungen", description: "Download: diskrete verteilungen", fileUrl: `${PREFIX}/basic_06_de_diskrete_verteilungen.docx` },
  { name: "pruefung diskrete verteilungen", description: "Download: pruefung diskrete verteilungen", fileUrl: `${PREFIX}/basic_06_de_pruefung_diskrete_verteilungen.docx` },
  { name: "discrete distributions", description: "Download: discrete distributions", fileUrl: `${PREFIX}/basic_06_en_discrete_distributions.docx` },
  { name: "korrelation pearson spearman", description: "Download: korrelation pearson spearman", fileUrl: `${PREFIX}/basic_07_de_korrelation_pearson_spearman.docx` },
  { name: "pruefung korrelation pearson spearman", description: "Download: pruefung korrelation pearson spearman", fileUrl: `${PREFIX}/basic_07_de_pruefung_korrelation_pearson_spearman.docx` },
  { name: "correlation pearson spearman", description: "Download: correlation pearson spearman", fileUrl: `${PREFIX}/basic_07_en_correlation_pearson_spearman.docx` },
  { name: "exam correlation pearson spearman", description: "Download: exam correlation pearson spearman", fileUrl: `${PREFIX}/basic_07_en_exam_correlation_pearson_spearman.docx` },
  { name: "einfache lineare regression", description: "Download: einfache lineare regression", fileUrl: `${PREFIX}/basic_08_de_einfache_lineare_regression.docx` },
  { name: "pruefung einfache lineare regression", description: "Download: pruefung einfache lineare regression", fileUrl: `${PREFIX}/basic_08_de_pruefung_einfache_lineare_regression.docx` },
  { name: "exam simple linear regression", description: "Download: exam simple linear regression", fileUrl: `${PREFIX}/basic_08_en_exam_simple_linear_regression.docx` },
  { name: "simple linear regression", description: "Download: simple linear regression", fileUrl: `${PREFIX}/basic_08_en_simple_linear_regression.docx` },
  { name: "pruefung t test gruppenvergleich", description: "Download: pruefung t test gruppenvergleich", fileUrl: `${PREFIX}/basic_09_de_pruefung_t_test_gruppenvergleich.docx` },
  { name: "t test gruppenvergleich", description: "Download: t test gruppenvergleich", fileUrl: `${PREFIX}/basic_09_de_t_test_gruppenvergleich.docx` },
  { name: "exam t test group comparison", description: "Download: exam t test group comparison", fileUrl: `${PREFIX}/basic_09_en_exam_t_test_group_comparison.docx` },
  { name: "t test group comparison", description: "Download: t test group comparison", fileUrl: `${PREFIX}/basic_09_en_t_test_group_comparison.docx` },
  { name: "kreuztabellen kontingenzanalyse", description: "Download: kreuztabellen kontingenzanalyse", fileUrl: `${PREFIX}/basic_10_de_kreuztabellen_kontingenzanalyse.docx` },
  { name: "pruefung kreuztabellen kontingenzanalyse", description: "Download: pruefung kreuztabellen kontingenzanalyse", fileUrl: `${PREFIX}/basic_10_de_pruefung_kreuztabellen_kontingenzanalyse.docx` },
  { name: "crosstabs contingency analysis", description: "Download: crosstabs contingency analysis", fileUrl: `${PREFIX}/basic_10_en_crosstabs_contingency_analysis.docx` },
  { name: "chi quadrat tests", description: "Download: chi quadrat tests", fileUrl: `${PREFIX}/basic_11_de_chi_quadrat_tests.docx` },
  { name: "pruefung chi quadrat tests", description: "Download: pruefung chi quadrat tests", fileUrl: `${PREFIX}/basic_11_de_pruefung_chi_quadrat_tests.docx` },
  { name: "chi square tests", description: "Download: chi square tests", fileUrl: `${PREFIX}/basic_11_en_chi_square_tests.docx` },
  { name: "exam chi square tests", description: "Download: exam chi square tests", fileUrl: `${PREFIX}/basic_11_en_exam_chi_square_tests.docx` },
  { name: "fehlerrechnung", description: "Download: fehlerrechnung", fileUrl: `${PREFIX}/basic_12_de_fehlerrechnung.docx` },
  { name: "pruefung fehlerrechnung", description: "Download: pruefung fehlerrechnung", fileUrl: `${PREFIX}/basic_12_de_pruefung_fehlerrechnung.docx` },
  { name: "error calculation", description: "Download: error calculation", fileUrl: `${PREFIX}/basic_12_en_error_calculation.docx` },
  { name: "effektstaerken", description: "Download: effektstaerken", fileUrl: `${PREFIX}/basic_13_de_effektstaerken.docx` },
  { name: "pruefung effektstaerken", description: "Download: pruefung effektstaerken", fileUrl: `${PREFIX}/basic_13_de_pruefung_effektstaerken.docx` },
  { name: "effect sizes", description: "Download: effect sizes", fileUrl: `${PREFIX}/basic_13_en_effect_sizes.docx` },
  { name: "pruefung testtheorie reliabilitaet", description: "Download: pruefung testtheorie reliabilitaet", fileUrl: `${PREFIX}/basic_14_de_pruefung_testtheorie_reliabilitaet.docx` },
  { name: "testtheorie reliabilitaet", description: "Download: testtheorie reliabilitaet", fileUrl: `${PREFIX}/basic_14_de_testtheorie_reliabilitaet.docx` },
  { name: "test theory reliability", description: "Download: test theory reliability", fileUrl: `${PREFIX}/basic_14_en_test_theory_reliability.docx` },
  { name: "pruefung survey design", description: "Download: pruefung survey design", fileUrl: `${PREFIX}/basic_15_de_pruefung_survey_design.docx` },
  { name: "survey design", description: "Download: survey design", fileUrl: `${PREFIX}/basic_15_de_survey_design.docx` },
  { name: "exam survey design", description: "Download: exam survey design", fileUrl: `${PREFIX}/basic_15_en_exam_survey_design.docx` },
  { name: "survey design", description: "Download: survey design", fileUrl: `${PREFIX}/basic_15_en_survey_design.docx` },
  { name: "pruefung qualitative methoden ueberblick", description: "Download: pruefung qualitative methoden ueberblick", fileUrl: `${PREFIX}/basic_16_de_pruefung_qualitative_methoden_ueberblick.docx` },
  { name: "qualitative methoden ueberblick", description: "Download: qualitative methoden ueberblick", fileUrl: `${PREFIX}/basic_16_de_qualitative_methoden_ueberblick.docx` },
  { name: "exam qualitative methods overview", description: "Download: exam qualitative methods overview", fileUrl: `${PREFIX}/basic_16_en_exam_qualitative_methods_overview.docx` },
  { name: "qualitative methods overview", description: "Download: qualitative methods overview", fileUrl: `${PREFIX}/basic_16_en_qualitative_methods_overview.docx` },
]

const STANDARD_EXTRA: DownloadItem[] = [
  { name: "exam questions", description: "Download: exam questions", fileUrl: `${PREFIX}/standard_01_de_exam_questions.docx` },
  { name: "pruefung wissenschaftstheorie", description: "Download: pruefung wissenschaftstheorie", fileUrl: `${PREFIX}/standard_01_de_pruefung_wissenschaftstheorie.docx` },
  { name: "spickzettel", description: "Download: spickzettel", fileUrl: `${PREFIX}/standard_01_de_spickzettel.docx` },
  { name: "wissenschaftstheorie", description: "Download: wissenschaftstheorie", fileUrl: `${PREFIX}/standard_01_de_wissenschaftstheorie.docx` },
  { name: "wörterbuch", description: "Download: wörterbuch", fileUrl: `${PREFIX}/standard_01_de_wörterbuch.docx` },
  { name: "cheatsheet", description: "Download: cheatsheet", fileUrl: `${PREFIX}/standard_01_en_cheatsheet.docx` },
  { name: "dictionary", description: "Download: dictionary", fileUrl: `${PREFIX}/standard_01_en_dictionary.docx` },
  { name: "exam philosophy of science", description: "Download: exam philosophy of science", fileUrl: `${PREFIX}/standard_01_en_exam_philosophy_of_science.docx` },
  { name: "exam questions", description: "Download: exam questions", fileUrl: `${PREFIX}/standard_01_en_exam_questions.docx` },
  { name: "philosophy of science", description: "Download: philosophy of science", fileUrl: `${PREFIX}/standard_01_en_philosophy_of_science.docx` },
  { name: "code r", description: "Download: code r", fileUrl: `${PREFIX}/standard_02_code_r.R` },
  { name: "experimentelles design", description: "Download: experimentelles design", fileUrl: `${PREFIX}/standard_02_de_experimentelles_design.docx` },
  { name: "pruefung experimentelles design", description: "Download: pruefung experimentelles design", fileUrl: `${PREFIX}/standard_02_de_pruefung_experimentelles_design.docx` },
  { name: "exam experimental design", description: "Download: exam experimental design", fileUrl: `${PREFIX}/standard_02_en_exam_experimental_design.docx` },
  { name: "experimental design", description: "Download: experimental design", fileUrl: `${PREFIX}/standard_02_en_experimental_design.docx` },
  { name: "code spss", description: "Download: code spss", fileUrl: `${PREFIX}/standard_03_code_spss.sps` },
  { name: "multiple lineare regression", description: "Download: multiple lineare regression", fileUrl: `${PREFIX}/standard_03_de_multiple_lineare_regression.docx` },
  { name: "pruefung multiple lineare regression", description: "Download: pruefung multiple lineare regression", fileUrl: `${PREFIX}/standard_03_de_pruefung_multiple_lineare_regression.docx` },
  { name: "exam multiple linear regression", description: "Download: exam multiple linear regression", fileUrl: `${PREFIX}/standard_03_en_exam_multiple_linear_regression.docx` },
  { name: "multiple linear regression", description: "Download: multiple linear regression", fileUrl: `${PREFIX}/standard_03_en_multiple_linear_regression.docx` },
  { name: "einführung R", description: "Download: einführung R", fileUrl: `${PREFIX}/standard_04_de_einführung_R.docx` },
  { name: "nichtlineare regression", description: "Download: nichtlineare regression", fileUrl: `${PREFIX}/standard_04_de_nichtlineare_regression.docx` },
  { name: "pruefung nichtlineare regression", description: "Download: pruefung nichtlineare regression", fileUrl: `${PREFIX}/standard_04_de_pruefung_nichtlineare_regression.docx` },
  { name: "introduction R", description: "Download: introduction R", fileUrl: `${PREFIX}/standard_04_en_introduction_R.docx` },
  { name: "nonlinear regression", description: "Download: nonlinear regression", fileUrl: `${PREFIX}/standard_04_en_nonlinear_regression.docx` },
  { name: "einführung python", description: "Download: einführung python", fileUrl: `${PREFIX}/standard_05_de_einführung_python.docx` },
  { name: "logistische regression", description: "Download: logistische regression", fileUrl: `${PREFIX}/standard_05_de_logistische_regression.docx` },
  { name: "pruefung logistische regression", description: "Download: pruefung logistische regression", fileUrl: `${PREFIX}/standard_05_de_pruefung_logistische_regression.docx` },
  { name: "exam logistic regression", description: "Download: exam logistic regression", fileUrl: `${PREFIX}/standard_05_en_exam_logistic_regression.docx` },
  { name: "introduction python", description: "Download: introduction python", fileUrl: `${PREFIX}/standard_05_en_introduction_python.docx` },
  { name: "logistic regression", description: "Download: logistic regression", fileUrl: `${PREFIX}/standard_05_en_logistic_regression.docx` },
  { name: "einführung spss", description: "Download: einführung spss", fileUrl: `${PREFIX}/standard_06_de_einführung_spss.docx` },
  { name: "moderation mediation", description: "Download: moderation mediation", fileUrl: `${PREFIX}/standard_06_de_moderation_mediation.docx` },
  { name: "pruefung moderation mediation", description: "Download: pruefung moderation mediation", fileUrl: `${PREFIX}/standard_06_de_pruefung_moderation_mediation.docx` },
  { name: "introduction spss", description: "Download: introduction spss", fileUrl: `${PREFIX}/standard_06_en_introduction_spss.docx` },
  { name: "moderation mediation", description: "Download: moderation mediation", fileUrl: `${PREFIX}/standard_06_en_moderation_mediation.docx` },
  { name: "anova einfaktoriell", description: "Download: anova einfaktoriell", fileUrl: `${PREFIX}/standard_07_de_anova_einfaktoriell.docx` },
  { name: "pruefung anova einfaktoriell", description: "Download: pruefung anova einfaktoriell", fileUrl: `${PREFIX}/standard_07_de_pruefung_anova_einfaktoriell.docx` },
  { name: "exam one way anova", description: "Download: exam one way anova", fileUrl: `${PREFIX}/standard_07_en_exam_one_way_anova.docx` },
  { name: "one way anova", description: "Download: one way anova", fileUrl: `${PREFIX}/standard_07_en_one_way_anova.docx` },
  { name: "messwiederholung", description: "Download: messwiederholung", fileUrl: `${PREFIX}/standard_09_de_messwiederholung.docx` },
  { name: "pruefung messwiederholung", description: "Download: pruefung messwiederholung", fileUrl: `${PREFIX}/standard_09_de_pruefung_messwiederholung.docx` },
  { name: "repeated measures", description: "Download: repeated measures", fileUrl: `${PREFIX}/standard_09_en_repeated_measures.docx` },
  { name: "nichtparametrische tests", description: "Download: nichtparametrische tests", fileUrl: `${PREFIX}/standard_10_de_nichtparametrische_tests.docx` },
  { name: "pruefung nichtparametrische tests", description: "Download: pruefung nichtparametrische tests", fileUrl: `${PREFIX}/standard_10_de_pruefung_nichtparametrische_tests.docx` },
  { name: "exam nonparametric tests", description: "Download: exam nonparametric tests", fileUrl: `${PREFIX}/standard_10_en_exam_nonparametric_tests.docx` },
  { name: "nonparametric tests", description: "Download: nonparametric tests", fileUrl: `${PREFIX}/standard_10_en_nonparametric_tests.docx` },
  { name: "poweranalyse", description: "Download: poweranalyse", fileUrl: `${PREFIX}/standard_11_de_poweranalyse.docx` },
  { name: "pruefung poweranalyse", description: "Download: pruefung poweranalyse", fileUrl: `${PREFIX}/standard_11_de_pruefung_poweranalyse.docx` },
  { name: "exam power analysis", description: "Download: exam power analysis", fileUrl: `${PREFIX}/standard_11_en_exam_power_analysis.docx` },
  { name: "power analysis", description: "Download: power analysis", fileUrl: `${PREFIX}/standard_11_en_power_analysis.docx` },
  { name: "pca hauptkomponentenanalyse", description: "Download: pca hauptkomponentenanalyse", fileUrl: `${PREFIX}/standard_12_de_pca_hauptkomponentenanalyse.docx` },
  { name: "pruefung pca hauptkomponentenanalyse", description: "Download: pruefung pca hauptkomponentenanalyse", fileUrl: `${PREFIX}/standard_12_de_pruefung_pca_hauptkomponentenanalyse.docx` },
  { name: "pca principal component analysis", description: "Download: pca principal component analysis", fileUrl: `${PREFIX}/standard_12_en_pca_principal_component_analysis.docx` },
  { name: "diskriminanzanalyse", description: "Download: diskriminanzanalyse", fileUrl: `${PREFIX}/standard_13_de_diskriminanzanalyse.docx` },
  { name: "pruefung diskriminanzanalyse", description: "Download: pruefung diskriminanzanalyse", fileUrl: `${PREFIX}/standard_13_de_pruefung_diskriminanzanalyse.docx` },
  { name: "discriminant analysis", description: "Download: discriminant analysis", fileUrl: `${PREFIX}/standard_13_en_discriminant_analysis.docx` },
  { name: "pruefung quasi experimentelle designs", description: "Download: pruefung quasi experimentelle designs", fileUrl: `${PREFIX}/standard_17_de_pruefung_quasi_experimentelle_designs.docx` },
  { name: "quasi experimentelle designs", description: "Download: quasi experimentelle designs", fileUrl: `${PREFIX}/standard_17_de_quasi_experimentelle_designs.docx` },
  { name: "quasi experimental designs", description: "Download: quasi experimental designs", fileUrl: `${PREFIX}/standard_17_en_quasi_experimental_designs.docx` },
  { name: "multinomiale regression", description: "Download: multinomiale regression", fileUrl: `${PREFIX}/standard_18_de_multinomiale_regression.docx` },
  { name: "pruefung multinomiale regression", description: "Download: pruefung multinomiale regression", fileUrl: `${PREFIX}/standard_18_de_pruefung_multinomiale_regression.docx` },
  { name: "multinomial regression", description: "Download: multinomial regression", fileUrl: `${PREFIX}/standard_18_en_multinomial_regression.docx` },
  { name: "pruefung qualitatives interview", description: "Download: pruefung qualitatives interview", fileUrl: `${PREFIX}/standard_19_de_pruefung_qualitatives_interview.docx` },
  { name: "qualitatives interview", description: "Download: qualitatives interview", fileUrl: `${PREFIX}/standard_19_de_qualitatives_interview.docx` },
  { name: "exam qualitative interview", description: "Download: exam qualitative interview", fileUrl: `${PREFIX}/standard_19_en_exam_qualitative_interview.docx` },
  { name: "qualitative interview", description: "Download: qualitative interview", fileUrl: `${PREFIX}/standard_19_en_qualitative_interview.docx` },
  { name: "inhaltsanalyse mayring", description: "Download: inhaltsanalyse mayring", fileUrl: `${PREFIX}/standard_20_de_inhaltsanalyse_mayring.docx` },
  { name: "pruefung inhaltsanalyse mayring", description: "Download: pruefung inhaltsanalyse mayring", fileUrl: `${PREFIX}/standard_20_de_pruefung_inhaltsanalyse_mayring.docx` },
  { name: "content analysis mayring", description: "Download: content analysis mayring", fileUrl: `${PREFIX}/standard_20_en_content_analysis_mayring.docx` },
  { name: "exam content analysis mayring", description: "Download: exam content analysis mayring", fileUrl: `${PREFIX}/standard_20_en_exam_content_analysis_mayring.docx` },
  { name: "diskursanalyse", description: "Download: diskursanalyse", fileUrl: `${PREFIX}/standard_21_de_diskursanalyse.docx` },
  { name: "pruefung diskursanalyse", description: "Download: pruefung diskursanalyse", fileUrl: `${PREFIX}/standard_21_de_pruefung_diskursanalyse.docx` },
  { name: "discourse analysis", description: "Download: discourse analysis", fileUrl: `${PREFIX}/standard_21_en_discourse_analysis.docx` },
  { name: "exam discourse analysis", description: "Download: exam discourse analysis", fileUrl: `${PREFIX}/standard_21_en_exam_discourse_analysis.docx` },
]

const ADVANCED_EXTRA: DownloadItem[] = [
  { name: "code r", description: "Download: code r", fileUrl: `${PREFIX}/advanced_02_code_r.R` },
  { name: "fehlende werte mi", description: "Download: fehlende werte mi", fileUrl: `${PREFIX}/advanced_02_de_fehlende_werte_mi.docx` },
  { name: "pruefung fehlende werte mi", description: "Download: pruefung fehlende werte mi", fileUrl: `${PREFIX}/advanced_02_de_pruefung_fehlende_werte_mi.docx` },
  { name: "missing data mi", description: "Download: missing data mi", fileUrl: `${PREFIX}/advanced_02_en_missing_data_mi.docx` },
  { name: "code spss", description: "Download: code spss", fileUrl: `${PREFIX}/advanced_03_code_spss.sps` },
  { name: "panel laengsschnitt", description: "Download: panel laengsschnitt", fileUrl: `${PREFIX}/advanced_03_de_panel_laengsschnitt.docx` },
  { name: "pruefung panel laengsschnitt", description: "Download: pruefung panel laengsschnitt", fileUrl: `${PREFIX}/advanced_03_de_pruefung_panel_laengsschnitt.docx` },
  { name: "panel longitudinal", description: "Download: panel longitudinal", fileUrl: `${PREFIX}/advanced_03_en_panel_longitudinal.docx` },
  { name: "einführung R", description: "Download: einführung R", fileUrl: `${PREFIX}/advanced_04_de_einführung_R.docx` },
  { name: "faktorenanalyse efa cfa", description: "Download: faktorenanalyse efa cfa", fileUrl: `${PREFIX}/advanced_04_de_faktorenanalyse_efa_cfa.docx` },
  { name: "pruefung faktorenanalyse efa cfa", description: "Download: pruefung faktorenanalyse efa cfa", fileUrl: `${PREFIX}/advanced_04_de_pruefung_faktorenanalyse_efa_cfa.docx` },
  { name: "exam factor analysis efa cfa", description: "Download: exam factor analysis efa cfa", fileUrl: `${PREFIX}/advanced_04_en_exam_factor_analysis_efa_cfa.docx` },
  { name: "factor analysis efa cfa", description: "Download: factor analysis efa cfa", fileUrl: `${PREFIX}/advanced_04_en_factor_analysis_efa_cfa.docx` },
  { name: "introduction R", description: "Download: introduction R", fileUrl: `${PREFIX}/advanced_04_en_introduction_R.docx` },
  { name: "anova ancova mehrfaktoriell", description: "Download: anova ancova mehrfaktoriell", fileUrl: `${PREFIX}/advanced_05_de_anova_ancova_mehrfaktoriell.docx` },
  { name: "einführung python", description: "Download: einführung python", fileUrl: `${PREFIX}/advanced_05_de_einführung_python.docx` },
  { name: "pruefung anova ancova mehrfaktoriell", description: "Download: pruefung anova ancova mehrfaktoriell", fileUrl: `${PREFIX}/advanced_05_de_pruefung_anova_ancova_mehrfaktoriell.docx` },
  { name: "anova ancova factorial", description: "Download: anova ancova factorial", fileUrl: `${PREFIX}/advanced_05_en_anova_ancova_factorial.docx` },
  { name: "exam anova ancova factorial", description: "Download: exam anova ancova factorial", fileUrl: `${PREFIX}/advanced_05_en_exam_anova_ancova_factorial.docx` },
  { name: "introduction python", description: "Download: introduction python", fileUrl: `${PREFIX}/advanced_05_en_introduction_python.docx` },
  { name: "einführung spss", description: "Download: einführung spss", fileUrl: `${PREFIX}/advanced_06_de_einführung_spss.docx` },
  { name: "mixed methods", description: "Download: mixed methods", fileUrl: `${PREFIX}/advanced_06_de_mixed_methods.docx` },
  { name: "pruefung mixed methods", description: "Download: pruefung mixed methods", fileUrl: `${PREFIX}/advanced_06_de_pruefung_mixed_methods.docx` },
  { name: "exam mixed methods", description: "Download: exam mixed methods", fileUrl: `${PREFIX}/advanced_06_en_exam_mixed_methods.docx` },
  { name: "introduction spss", description: "Download: introduction spss", fileUrl: `${PREFIX}/advanced_06_en_introduction_spss.docx` },
  { name: "mixed methods", description: "Download: mixed methods", fileUrl: `${PREFIX}/advanced_06_en_mixed_methods.docx` },
  { name: "erkenntnistheorie ontologie", description: "Download: erkenntnistheorie ontologie", fileUrl: `${PREFIX}/advanced_07_de_erkenntnistheorie_ontologie.docx` },
  { name: "pruefung erkenntnistheorie ontologie", description: "Download: pruefung erkenntnistheorie ontologie", fileUrl: `${PREFIX}/advanced_07_de_pruefung_erkenntnistheorie_ontologie.docx` },
  { name: "epistemology ontology", description: "Download: epistemology ontology", fileUrl: `${PREFIX}/advanced_07_en_epistemology_ontology.docx` },
  { name: "exam epistemology ontology", description: "Download: exam epistemology ontology", fileUrl: `${PREFIX}/advanced_07_en_exam_epistemology_ontology.docx` },
  { name: "grounded theory", description: "Download: grounded theory", fileUrl: `${PREFIX}/advanced_08_de_grounded_theory.docx` },
  { name: "pruefung grounded theory", description: "Download: pruefung grounded theory", fileUrl: `${PREFIX}/advanced_08_de_pruefung_grounded_theory.docx` },
  { name: "exam grounded theory", description: "Download: exam grounded theory", fileUrl: `${PREFIX}/advanced_08_en_exam_grounded_theory.docx` },
  { name: "grounded theory", description: "Download: grounded theory", fileUrl: `${PREFIX}/advanced_08_en_grounded_theory.docx` },
  { name: "pruefung qualitative beobachtung ethnographie", description: "Download: pruefung qualitative beobachtung ethnographie", fileUrl: `${PREFIX}/advanced_09_de_pruefung_qualitative_beobachtung_ethnographie.docx` },
  { name: "qualitative beobachtung ethnographie", description: "Download: qualitative beobachtung ethnographie", fileUrl: `${PREFIX}/advanced_09_de_qualitative_beobachtung_ethnographie.docx` },
  { name: "exam qualitative observation ethnography", description: "Download: exam qualitative observation ethnography", fileUrl: `${PREFIX}/advanced_09_en_exam_qualitative_observation_ethnography.docx` },
  { name: "qualitative observation ethnography", description: "Download: qualitative observation ethnography", fileUrl: `${PREFIX}/advanced_09_en_qualitative_observation_ethnography.docx` },
  { name: "propensity score matching", description: "Download: propensity score matching", fileUrl: `${PREFIX}/advanced_10_de_propensity_score_matching.docx` },
  { name: "pruefung propensity score matching", description: "Download: pruefung propensity score matching", fileUrl: `${PREFIX}/advanced_10_de_pruefung_propensity_score_matching.docx` },
  { name: "exam propensity score matching", description: "Download: exam propensity score matching", fileUrl: `${PREFIX}/advanced_10_en_exam_propensity_score_matching.docx` },
  { name: "manova", description: "Download: manova", fileUrl: `${PREFIX}/advanced_11_de_manova.docx` },
  { name: "pruefung manova", description: "Download: pruefung manova", fileUrl: `${PREFIX}/advanced_11_de_pruefung_manova.docx` },
  { name: "manova", description: "Download: manova", fileUrl: `${PREFIX}/advanced_11_en_manova.docx` },
  { name: "clusteranalyse", description: "Download: clusteranalyse", fileUrl: `${PREFIX}/advanced_12_de_clusteranalyse.docx` },
  { name: "pruefung clusteranalyse", description: "Download: pruefung clusteranalyse", fileUrl: `${PREFIX}/advanced_12_de_pruefung_clusteranalyse.docx` },
  { name: "cluster analysis", description: "Download: cluster analysis", fileUrl: `${PREFIX}/advanced_12_en_cluster_analysis.docx` },
  { name: "pruefung roc analyse", description: "Download: pruefung roc analyse", fileUrl: `${PREFIX}/advanced_13_de_pruefung_roc_analyse.docx` },
  { name: "roc analyse", description: "Download: roc analyse", fileUrl: `${PREFIX}/advanced_13_de_roc_analyse.docx` },
  { name: "roc analysis", description: "Download: roc analysis", fileUrl: `${PREFIX}/advanced_13_en_roc_analysis.docx` },
  { name: "pruefung ueberlebenszeitanalyse", description: "Download: pruefung ueberlebenszeitanalyse", fileUrl: `${PREFIX}/advanced_14_de_pruefung_ueberlebenszeitanalyse.docx` },
  { name: "ueberlebenszeitanalyse", description: "Download: ueberlebenszeitanalyse", fileUrl: `${PREFIX}/advanced_14_de_ueberlebenszeitanalyse.docx` },
  { name: "survival analysis", description: "Download: survival analysis", fileUrl: `${PREFIX}/advanced_14_en_survival_analysis.docx` },
]

const ALL_ACCESS_EXTRA: DownloadItem[] = [
  { name: "01 de optimierung numerische verfahren", description: "Download: 01 de optimierung numerische verfahren", fileUrl: `${PREFIX}/full_access_01_de_optimierung_numerische_verfahren.docx` },
  { name: "01 de pruefung optimierung numerische verfahren", description: "Download: 01 de pruefung optimierung numerische verfahren", fileUrl: `${PREFIX}/full_access_01_de_pruefung_optimierung_numerische_verfahren.docx` },
  { name: "01 de spickzettel", description: "Download: 01 de spickzettel", fileUrl: `${PREFIX}/full_access_01_de_spickzettel.docx` },
  { name: "01 de wörterbuch", description: "Download: 01 de wörterbuch", fileUrl: `${PREFIX}/full_access_01_de_wörterbuch.docx` },
  { name: "01 en cheatsheet", description: "Download: 01 en cheatsheet", fileUrl: `${PREFIX}/full_access_01_en_cheatsheet.docx` },
  { name: "01 en dictionary", description: "Download: 01 en dictionary", fileUrl: `${PREFIX}/full_access_01_en_dictionary.docx` },
  { name: "01 en exam optimization numerical methods", description: "Download: 01 en exam optimization numerical methods", fileUrl: `${PREFIX}/full_access_01_en_exam_optimization_numerical_methods.docx` },
  { name: "01 en optimization numerical methods", description: "Download: 01 en optimization numerical methods", fileUrl: `${PREFIX}/full_access_01_en_optimization_numerical_methods.docx` },
  { name: "02 de machine learning supervised", description: "Download: 02 de machine learning supervised", fileUrl: `${PREFIX}/full_access_02_de_machine_learning_supervised.docx` },
  { name: "02 de pruefung machine learning supervised", description: "Download: 02 de pruefung machine learning supervised", fileUrl: `${PREFIX}/full_access_02_de_pruefung_machine_learning_supervised.docx` },
  { name: "02 en exam supervised learning", description: "Download: 02 en exam supervised learning", fileUrl: `${PREFIX}/full_access_02_en_exam_supervised_learning.docx` },
  { name: "02 en supervised learning", description: "Download: 02 en supervised learning", fileUrl: `${PREFIX}/full_access_02_en_supervised_learning.docx` },
  { name: "03 de machine learning unsupervised", description: "Download: 03 de machine learning unsupervised", fileUrl: `${PREFIX}/full_access_03_de_machine_learning_unsupervised.docx` },
  { name: "03 de pruefung machine learning unsupervised", description: "Download: 03 de pruefung machine learning unsupervised", fileUrl: `${PREFIX}/full_access_03_de_pruefung_machine_learning_unsupervised.docx` },
  { name: "03 en exam unsupervised learning", description: "Download: 03 en exam unsupervised learning", fileUrl: `${PREFIX}/full_access_03_en_exam_unsupervised_learning.docx` },
  { name: "03 en unsupervised learning", description: "Download: 03 en unsupervised learning", fileUrl: `${PREFIX}/full_access_03_en_unsupervised_learning.docx` },
  { name: "04 de deep learning neuronale netze", description: "Download: 04 de deep learning neuronale netze", fileUrl: `${PREFIX}/full_access_04_de_deep_learning_neuronale_netze.docx` },
  { name: "04 de pruefung deep learning neuronale netze", description: "Download: 04 de pruefung deep learning neuronale netze", fileUrl: `${PREFIX}/full_access_04_de_pruefung_deep_learning_neuronale_netze.docx` },
  { name: "04 en deep learning neural networks", description: "Download: 04 en deep learning neural networks", fileUrl: `${PREFIX}/full_access_04_en_deep_learning_neural_networks.docx` },
  { name: "04 en exam deep learning neural networks", description: "Download: 04 en exam deep learning neural networks", fileUrl: `${PREFIX}/full_access_04_en_exam_deep_learning_neural_networks.docx` },
  { name: "05 de hyperparameter optimization", description: "Download: 05 de hyperparameter optimization", fileUrl: `${PREFIX}/full_access_05_de_hyperparameter_optimization.docx` },
  { name: "05 de pruefung hyperparameter optimization", description: "Download: 05 de pruefung hyperparameter optimization", fileUrl: `${PREFIX}/full_access_05_de_pruefung_hyperparameter_optimization.docx` },
  { name: "05 en exam hyperparameter optimization", description: "Download: 05 en exam hyperparameter optimization", fileUrl: `${PREFIX}/full_access_05_en_exam_hyperparameter_optimization.docx` },
  { name: "06 de bayesian statistics", description: "Download: 06 de bayesian statistics", fileUrl: `${PREFIX}/full_access_06_de_bayesian_statistics.docx` },
  { name: "06 de pruefung bayesian statistics", description: "Download: 06 de pruefung bayesian statistics", fileUrl: `${PREFIX}/full_access_06_de_pruefung_bayesian_statistics.docx` },
  { name: "06 en bayesian statistics", description: "Download: 06 en bayesian statistics", fileUrl: `${PREFIX}/full_access_06_en_bayesian_statistics.docx` },
  { name: "06 en exam bayesian statistics", description: "Download: 06 en exam bayesian statistics", fileUrl: `${PREFIX}/full_access_06_en_exam_bayesian_statistics.docx` },
  { name: "07 de bayesian time series zustandsraum", description: "Download: 07 de bayesian time series zustandsraum", fileUrl: `${PREFIX}/full_access_07_de_bayesian_time_series_zustandsraum.docx` },
  { name: "07 de pruefung bayesian time series zustandsraum", description: "Download: 07 de pruefung bayesian time series zustandsraum", fileUrl: `${PREFIX}/full_access_07_de_pruefung_bayesian_time_series_zustandsraum.docx` },
  { name: "07 en bayesian time series state space", description: "Download: 07 en bayesian time series state space", fileUrl: `${PREFIX}/full_access_07_en_bayesian_time_series_state_space.docx` },
  { name: "07 en exam bayesian time series state space", description: "Download: 07 en exam bayesian time series state space", fileUrl: `${PREFIX}/full_access_07_en_exam_bayesian_time_series_state_space.docx` },
  { name: "08 de kausale inferenz treatment", description: "Download: 08 de kausale inferenz treatment", fileUrl: `${PREFIX}/full_access_08_de_kausale_inferenz_treatment.docx` },
  { name: "08 de pruefung kausale inferenz treatment", description: "Download: 08 de pruefung kausale inferenz treatment", fileUrl: `${PREFIX}/full_access_08_de_pruefung_kausale_inferenz_treatment.docx` },
  { name: "08 en causal inference treatment", description: "Download: 08 en causal inference treatment", fileUrl: `${PREFIX}/full_access_08_en_causal_inference_treatment.docx` },
  { name: "08 en exam causal inference treatment", description: "Download: 08 en exam causal inference treatment", fileUrl: `${PREFIX}/full_access_08_en_exam_causal_inference_treatment.docx` },
  { name: "09 de pruefung sem strukturgleichungsmodelle", description: "Download: 09 de pruefung sem strukturgleichungsmodelle", fileUrl: `${PREFIX}/full_access_09_de_pruefung_sem_strukturgleichungsmodelle.docx` },
  { name: "09 de sem strukturgleichungsmodelle", description: "Download: 09 de sem strukturgleichungsmodelle", fileUrl: `${PREFIX}/full_access_09_de_sem_strukturgleichungsmodelle.docx` },
  { name: "09 en sem structural equation modeling", description: "Download: 09 en sem structural equation modeling", fileUrl: `${PREFIX}/full_access_09_en_sem_structural_equation_modeling.docx` },
  { name: "1 de entscheidungsbaum welcher test", description: "Download: 1 de entscheidungsbaum welcher test", fileUrl: `${PREFIX}/full_access_1_de_entscheidungsbaum_welcher_test.docx` },
  { name: "1 en decision tree which test", description: "Download: 1 en decision tree which test", fileUrl: `${PREFIX}/full_access_1_en_decision_tree_which_test.docx` },
  { name: "10 de item response theorie", description: "Download: 10 de item response theorie", fileUrl: `${PREFIX}/full_access_10_de_item_response_theorie.docx` },
  { name: "10 de pruefung item response theorie", description: "Download: 10 de pruefung item response theorie", fileUrl: `${PREFIX}/full_access_10_de_pruefung_item_response_theorie.docx` },
  { name: "10 en item response theory", description: "Download: 10 en item response theory", fileUrl: `${PREFIX}/full_access_10_en_item_response_theory.docx` },
  { name: "11 de pruefung zeitreihenanalyse", description: "Download: 11 de pruefung zeitreihenanalyse", fileUrl: `${PREFIX}/full_access_11_de_pruefung_zeitreihenanalyse.docx` },
  { name: "11 de zeitreihenanalyse", description: "Download: 11 de zeitreihenanalyse", fileUrl: `${PREFIX}/full_access_11_de_zeitreihenanalyse.docx` },
  { name: "11 en exam time series analysis", description: "Download: 11 en exam time series analysis", fileUrl: `${PREFIX}/full_access_11_en_exam_time_series_analysis.docx` },
  { name: "11 en time series analysis", description: "Download: 11 en time series analysis", fileUrl: `${PREFIX}/full_access_11_en_time_series_analysis.docx` },
  { name: "12 de mehrebenenanalyse multilevel", description: "Download: 12 de mehrebenenanalyse multilevel", fileUrl: `${PREFIX}/full_access_12_de_mehrebenenanalyse_multilevel.docx` },
  { name: "12 de pruefung mehrebenenanalyse multilevel", description: "Download: 12 de pruefung mehrebenenanalyse multilevel", fileUrl: `${PREFIX}/full_access_12_de_pruefung_mehrebenenanalyse_multilevel.docx` },
  { name: "12 en exam multilevel analysis", description: "Download: 12 en exam multilevel analysis", fileUrl: `${PREFIX}/full_access_12_en_exam_multilevel_analysis.docx` },
  { name: "12 en multilevel analysis", description: "Download: 12 en multilevel analysis", fileUrl: `${PREFIX}/full_access_12_en_multilevel_analysis.docx` },
  { name: "13 de pruefung systematic reviews meta analyse", description: "Download: 13 de pruefung systematic reviews meta analyse", fileUrl: `${PREFIX}/full_access_13_de_pruefung_systematic_reviews_meta_analyse.docx` },
  { name: "13 de systematic reviews meta analyse", description: "Download: 13 de systematic reviews meta analyse", fileUrl: `${PREFIX}/full_access_13_de_systematic_reviews_meta_analyse.docx` },
  { name: "13 en exam systematic reviews meta analysis", description: "Download: 13 en exam systematic reviews meta analysis", fileUrl: `${PREFIX}/full_access_13_en_exam_systematic_reviews_meta_analysis.docx` },
  { name: "13 en systematic reviews meta analysis", description: "Download: 13 en systematic reviews meta analysis", fileUrl: `${PREFIX}/full_access_13_en_systematic_reviews_meta_analysis.docx` },
  { name: "14 de bootstrap resampling", description: "Download: 14 de bootstrap resampling", fileUrl: `${PREFIX}/full_access_14_de_bootstrap_resampling.docx` },
  { name: "14 de exam questions", description: "Download: 14 de exam questions", fileUrl: `${PREFIX}/full_access_14_de_exam_questions.docx` },
  { name: "14 de pruefung bootstrap resampling", description: "Download: 14 de pruefung bootstrap resampling", fileUrl: `${PREFIX}/full_access_14_de_pruefung_bootstrap_resampling.docx` },
  { name: "14 de spickzettel", description: "Download: 14 de spickzettel", fileUrl: `${PREFIX}/full_access_14_de_spickzettel.docx` },
  { name: "14 de wörterbuch", description: "Download: 14 de wörterbuch", fileUrl: `${PREFIX}/full_access_14_de_wörterbuch.docx` },
  { name: "14 en bootstrap resampling", description: "Download: 14 en bootstrap resampling", fileUrl: `${PREFIX}/full_access_14_en_bootstrap_resampling.docx` },
  { name: "14 en cheatsheet", description: "Download: 14 en cheatsheet", fileUrl: `${PREFIX}/full_access_14_en_cheatsheet.docx` },
  { name: "14 en dictionary", description: "Download: 14 en dictionary", fileUrl: `${PREFIX}/full_access_14_en_dictionary.docx` },
  { name: "14 en exam bootstrap resampling", description: "Download: 14 en exam bootstrap resampling", fileUrl: `${PREFIX}/full_access_14_en_exam_bootstrap_resampling.docx` },
  { name: "14 en exam questions", description: "Download: 14 en exam questions", fileUrl: `${PREFIX}/full_access_14_en_exam_questions.docx` },
  { name: "2 de literaturverzeichnis statistik methoden", description: "Download: 2 de literaturverzeichnis statistik methoden", fileUrl: `${PREFIX}/full_access_2_de_literaturverzeichnis_statistik_methoden.docx` },
  { name: "2 en bibliography statistics methods", description: "Download: 2 en bibliography statistics methods", fileUrl: `${PREFIX}/full_access_2_en_bibliography_statistics_methods.docx` },
  { name: "3 de literaturverzeichnis ergaenzende verfahren", description: "Download: 3 de literaturverzeichnis ergaenzende verfahren", fileUrl: `${PREFIX}/full_access_3_de_literaturverzeichnis_ergaenzende_verfahren.docx` },
  { name: "3 en bibliography supplementary methods", description: "Download: 3 en bibliography supplementary methods", fileUrl: `${PREFIX}/full_access_3_en_bibliography_supplementary_methods.docx` },
]
export const DOWNLOADS_PROD: Record<string, { items: DownloadItem[]; categories: string[] }> = {
  library_basics: {
    categories: ["Dossiers Grundlagen", "Prüfungen", "Spickzettel", "Wörterbuch"],
    items: [...BASIC_ITEMS],
  },
  library_standard: {
    categories: ["Alles aus Basics", "Dossiers Standard", "Prüfungen", "Code-Einführungen", "Klausurfragen"],
    items: [...BASIC_ITEMS, ...STANDARD_EXTRA],
  },
  library_advanced: {
    categories: ["Alles aus Standard", "Dossiers Advanced", "Prüfungen", "Code & Einführungen"],
    items: [...BASIC_ITEMS, ...STANDARD_EXTRA, ...ADVANCED_EXTRA],
  },
  library_all_access: {
    categories: ["Alles aus Advanced", "Dossiers PhD", "Prüfungen", "Literatur", "EN-Versionen"],
    items: [...BASIC_ITEMS, ...STANDARD_EXTRA, ...ADVANCED_EXTRA, ...ALL_ACCESS_EXTRA],
  },
}

export function getDownloadsProd(productKey: string) {
  return DOWNLOADS_PROD[productKey]?.items || []
}

export function getCategoriesProd(productKey: string) {
  return DOWNLOADS_PROD[productKey]?.categories || []
}